-- ============================================================================
-- ORGAS Reports Approval Workflow Schema
-- Migration: 02_create_reports_approval_workflow.sql
-- Purpose: Create tables for multi-stage approval workflow with feedback system
-- ============================================================================

-- ============================================================================
-- Enum Types for Approval Workflow
-- ============================================================================

CREATE TYPE public.approval_status_enum AS ENUM (
    'pendente',
    'aprovado',
    'reprovado'
);

CREATE TYPE public.parecer_type_enum AS ENUM (
    'pessoal',
    'fiscal',
    'contabil',
    'atendimento'
);

CREATE TYPE public.rejeicao_motivo_enum AS ENUM (
    'dados_inconsistentes',
    'calculo_errado',
    'campo_faltante',
    'interpretacao_incorreta',
    'dados_incompletos',
    'formato_invalido'
);

CREATE TYPE public.feedback_prioridade_enum AS ENUM (
    'critica',
    'alta',
    'media',
    'baixa'
);

CREATE TYPE public.feedback_status_enum AS ENUM (
    'novo',
    'em_analise',
    'corrigido',
    'nao_aplicavel'
);

-- ============================================================================
-- Main Approval Workflow Tables
-- ============================================================================

-- Table: relatorios_em_aprovacao
-- Purpose: Holds reports pending user approval
-- Stores the complete JSON response from agent for processing
CREATE TABLE IF NOT EXISTS public.relatorios_em_aprovacao (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    request_id VARCHAR(255) NOT NULL UNIQUE,
    task_id VARCHAR(255),
    report_id VARCHAR(255),

    -- Client & Context
    cliente_id VARCHAR(100) NOT NULL,
    cliente_nome VARCHAR(255) NOT NULL,

    -- Report Metadata
    tipo_parecer public.parecer_type_enum NOT NULL,
    data_geracao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Agent Response Data (JSON structure varies by tipo_parecer)
    response_data JSONB NOT NULL,  -- Complete structured response from agent

    -- Document Metrics
    documentos_analisados INT DEFAULT 0,
    etapas_executadas INT DEFAULT 0,

    -- Tracking
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    vencimento_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP + INTERVAL '7 days',

    -- Status
    status_aprovacao public.approval_status_enum DEFAULT 'pendente',

    -- Indexes
    CONSTRAINT valid_cliente_id CHECK (cliente_id != ''),
    CONSTRAINT valid_cliente_nome CHECK (cliente_nome != ''),
    CONSTRAINT valid_response_data CHECK (response_data IS NOT NULL)
);

CREATE INDEX idx_relatorios_em_aprovacao_cliente_id ON public.relatorios_em_aprovacao(cliente_id);
CREATE INDEX idx_relatorios_em_aprovacao_tipo_parecer ON public.relatorios_em_aprovacao(tipo_parecer);
CREATE INDEX idx_relatorios_em_aprovacao_data_geracao ON public.relatorios_em_aprovacao(data_geracao DESC);
CREATE INDEX idx_relatorios_em_aprovacao_vencimento ON public.relatorios_em_aprovacao(vencimento_em);
CREATE INDEX idx_relatorios_em_aprovacao_status ON public.relatorios_em_aprovacao(status_aprovacao);

-- Table: relatorios_aprovados
-- Purpose: Holds approved reports for archival/retrieval
CREATE TABLE IF NOT EXISTS public.relatorios_aprovados (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    relatorio_original_id UUID NOT NULL REFERENCES public.relatorios_em_aprovacao(id) ON DELETE RESTRICT,

    -- Approval Metadata
    aprovado_por VARCHAR(255) NOT NULL,
    data_aprovacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    observacoes_aprovacao TEXT,

    -- Report Data
    response_data JSONB NOT NULL,  -- Copy of approved response

    -- HTML Output (pre-generated by agent to avoid rework)
    html_output TEXT,

    -- Tracking
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Indexes
    CONSTRAINT valid_aprovado_por CHECK (aprovado_por != '')
);

CREATE INDEX idx_relatorios_aprovados_original_id ON public.relatorios_aprovados(relatorio_original_id);
CREATE INDEX idx_relatorios_aprovados_data_aprovacao ON public.relatorios_aprovados(data_aprovacao DESC);
CREATE INDEX idx_relatorios_aprovados_aprovado_por ON public.relatorios_aprovados(aprovado_por);

-- Table: relatorios_reprovados
-- Purpose: Holds rejected reports with feedback for model training
CREATE TABLE IF NOT EXISTS public.relatorios_reprovados (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    relatorio_original_id UUID NOT NULL REFERENCES public.relatorios_em_aprovacao(id) ON DELETE RESTRICT,

    -- Rejection Metadata
    reprovado_por VARCHAR(255) NOT NULL,
    data_rejeicao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Primary Rejection Reason
    motivo_rejeicao public.rejeicao_motivo_enum NOT NULL,
    justificativa TEXT NOT NULL,

    -- Detailed Error Information (for model training)
    secoes_com_erro TEXT[],  -- Array of section names with errors
    campo_com_erro VARCHAR(255),  -- Specific field that has error
    valor_esperado VARCHAR(255),
    valor_recebido VARCHAR(255),

    -- Response Data (for comparison)
    response_data JSONB NOT NULL,

    -- Tracking
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Indexes
    CONSTRAINT valid_reprovado_por CHECK (reprovado_por != ''),
    CONSTRAINT valid_justificativa CHECK (justificativa != '')
);

CREATE INDEX idx_relatorios_reprovados_original_id ON public.relatorios_reprovados(relatorio_original_id);
CREATE INDEX idx_relatorios_reprovados_motivo ON public.relatorios_reprovados(motivo_rejeicao);
CREATE INDEX idx_relatorios_reprovados_data_rejeicao ON public.relatorios_reprovados(data_rejeicao DESC);
CREATE INDEX idx_relatorios_reprovados_reprovado_por ON public.relatorios_reprovados(reprovado_por);

-- ============================================================================
-- Model Training Feedback System
-- ============================================================================

-- Table: feedback_treinamento
-- Purpose: Aggregate rejection feedback for model fine-tuning analysis
CREATE TABLE IF NOT EXISTS public.feedback_treinamento (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tipo_parecer public.parecer_type_enum NOT NULL,

    -- Error Classification
    motivo_rejeicao public.rejeicao_motivo_enum NOT NULL,
    campo_com_erro VARCHAR(255) NOT NULL,
    secao VARCHAR(255),  -- Which section of the report (e.g., "Secao1_Faturamento")

    -- Error Pattern Tracking
    frequencia_erro INT DEFAULT 1,  -- Number of times this error occurred
    frequencia_atualizada_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Context for Training
    valor_esperado VARCHAR(255),
    valor_recebido VARCHAR(255),
    descricao_padrao_erro TEXT,

    -- Priority & Status
    prioridade public.feedback_prioridade_enum DEFAULT 'media',
    status public.feedback_status_enum DEFAULT 'novo',

    -- Tracking
    primeira_ocorrencia TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ultima_ocorrencia TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Notes for ML team
    notas_ml TEXT,

    -- Indexes for analysis
    CONSTRAINT valid_campo CHECK (campo_com_erro != '')
);

CREATE INDEX idx_feedback_tipo_parecer ON public.feedback_treinamento(tipo_parecer);
CREATE INDEX idx_feedback_motivo ON public.feedback_treinamento(motivo_rejeicao);
CREATE INDEX idx_feedback_campo ON public.feedback_treinamento(campo_com_erro);
CREATE INDEX idx_feedback_secao ON public.feedback_treinamento(secao);
CREATE INDEX idx_feedback_prioridade ON public.feedback_treinamento(prioridade);
CREATE INDEX idx_feedback_status ON public.feedback_treinamento(status);
CREATE INDEX idx_feedback_frequencia ON public.feedback_treinamento(frequencia_erro DESC);

-- ============================================================================
-- Audit Trail for Compliance
-- ============================================================================

-- Table: auditoria_relatorios
-- Purpose: Track all state changes for compliance and debugging
CREATE TABLE IF NOT EXISTS public.auditoria_relatorios (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    relatorio_id UUID NOT NULL,  -- References either aprovacao/aprovado/reprovado ID

    -- State Transition
    acao VARCHAR(100) NOT NULL CHECK (acao IN (
        'criado',
        'em_aprovacao',
        'aprovado',
        'reprovado',
        'data_alterada',
        'observacoes_alteradas'
    )),

    -- User & Session
    usuario_id VARCHAR(255) NOT NULL,
    usuario_nome VARCHAR(255),

    -- Details
    detalhes JSONB DEFAULT '{}',  -- Specific changes made

    -- Timestamps
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Indexes
    CONSTRAINT valid_usuario CHECK (usuario_id != '')
);

CREATE INDEX idx_auditoria_relatorios_relatorio_id ON public.auditoria_relatorios(relatorio_id);
CREATE INDEX idx_auditoria_relatorios_acao ON public.auditoria_relatorios(acao);
CREATE INDEX idx_auditoria_relatorios_usuario_id ON public.auditoria_relatorios(usuario_id);
CREATE INDEX idx_auditoria_relatorios_criado_em ON public.auditoria_relatorios(criado_em DESC);

-- ============================================================================
-- Triggers for Updated Timestamp
-- ============================================================================

CREATE TRIGGER update_relatorios_aprovados_updated_at BEFORE UPDATE ON public.relatorios_aprovados
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_relatorios_reprovados_updated_at BEFORE UPDATE ON public.relatorios_reprovados
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_relatorios_em_aprovacao_updated_at BEFORE UPDATE ON public.relatorios_em_aprovacao
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_feedback_treinamento_updated_at BEFORE UPDATE ON public.feedback_treinamento
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Add missing updated_at column to relatorios_em_aprovacao
-- ============================================================================

ALTER TABLE public.relatorios_em_aprovacao ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- ============================================================================
-- Grant Permissions
-- ============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON public.relatorios_em_aprovacao TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.relatorios_aprovados TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.relatorios_reprovados TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.feedback_treinamento TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.auditoria_relatorios TO app_user;

-- ============================================================================
-- Final Status
-- ============================================================================

SELECT 'Reports approval workflow schema created successfully!' as status;
SELECT count(*) as approval_tables FROM information_schema.tables
WHERE table_schema = 'public' AND table_name IN (
    'relatorios_em_aprovacao',
    'relatorios_aprovados',
    'relatorios_reprovados',
    'feedback_treinamento',
    'auditoria_relatorios'
);
